### ISSUE TITLE
Add a picture of an ice cream cone to index.html

### ISSUE THREAD

**Issue by dbarner1** [Lilborneo/Hello-World#1]

**Comment by dbarner1** [comment]
helllooooooo

**Comment by Lilborneo** [comment]
Hiiii! I’m on vacation! I shall do this when back!

**Comment by dbarner1** [comment]
Oh man that's right! Sunscreen!


On Mar 7, 2020 at 4:20 PM, Lilborneo <notifications@github.com> wrote:

Hiiii! I’m on vacation! I shall do this when back!

Sent from my iPhone

> On Mar 5, 2020, at 1:53 AM, Dave Barner <notifications@github.com> wrote:
>
> ﻿
> helllooooooo
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lilborneo/Hello-World/issues/1?email_source=notifications&email_token=AFQSV4C4J4ZLKEGMDUYBSZDRGK3AJA5CNFSM4KZNFDRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOEFUZA#issuecomment-596138596>,
or unsubscribe
